[build]
command = "npm i && npx prisma generate && npx babel src --out-dir dist --extensions \".js,.jsx\""
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200
