[build]
command = "npm install && npx prisma generate && npx prisma migrate deploy && npm run start"
publish = "public"

[functions]
directory = "netlify/functions/server"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/index"
status = 200