[build]
command = "npm i && npx prisma generate && npx prisma migrate deploy && npx babel src --out-dir dist --extensions \".js,.jsx\" && cross-env NODE_ENV=development && node src/server.js"
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[redirects]]
from = "/*"
to = "/.netlify/functions/server"
status = 200
