const INVALID_CREDENTIALS = "INVCRED01";
const ACCOUNT_LOCKED = "LOCKER01";
const INVALID_SUBSCRIPTION = "UNSUBS56";
const SERVER_PROBLEM = "SERVER_ERR_001";
const ACCESS_DENIED = "ACCESS_DENIED";
const DUPLICATE_FOUND = "DUPLICATE_FOUND";
const INVALID_DATABASE_PROCESS = "DATABASE_ROLLBACK_PROCESS";
const FIALED_DATABASE_PROCESS = "FAILED_DATABASE_PROCESS";
const INVALID_IDENTITY = "INVALID_IDENTITY";
const MIDTRANS_ERROR = "PAYMENTSHIP_FAILED";
const NULL_DATA = "NULL_DATA";
const INVALID_PARAMS = "INVALID_PARAMS_FORMAT";

module.exports = {
  INVALID_CREDENTIALS,
  ACCOUNT_LOCKED,
  INVALID_SUBSCRIPTION,
  SERVER_PROBLEM,
  ACCESS_DENIED,
  DUPLICATE_FOUND,
  INVALID_DATABASE_PROCESS,
  FIALED_DATABASE_PROCESS,
  INVALID_IDENTITY,
  MIDTRANS_ERROR,
  NULL_DATA,
  INVALID_PARAMS,
};
